[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PUBLIC_SITE_URL = "https://aldeyarksa.tech"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Custom headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'none';"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules for SEO
[[redirects]]
  from = "https://aldeyar-jeddah.netlify.app/*"
  to = "https://aldeyarksa.tech/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://aldeyar-jeddah.com/*"
  to = "https://aldeyarksa.tech/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.aldeyarksa.tech/*"
  to = "https://aldeyarksa.tech/:splat"
  status = 301
  force = true
